-- AlterTable
ALTER TABLE `PropertyImage` ADD COLUMN `category` ENUM('EXTERIOR', 'LIVING_ROOM', 'BEDROOM', 'KITCHEN', 'BATHROOM', 'DINING', 'BALCONY', 'FLOOR_PLAN', 'OTHER') NOT NULL DEFAULT 'OTHER';
